language: node_js
node_js:
  - 5.12
notifications:
  - wilmersondasilva@gmail.com
before_install:
  - npm install -g bower@1.7.9
  - npm install -g gulp@3.9.1
  - npm install -g karma-cli@1.0.1
  - npm install -g protractor@4.0.8
  - webdriver-manager update
  - bower install
#before_script:
  #- gulp 
script:
  - karma start config/karma.config.js --single-run --browsers PhantomJS